/**
 * UGC Similarity Level Calculator. Thresholds are never hardcoded here -
 * every call takes the current `ugc_levels` config rows (from
 * public_ugc_levels) as an argument.
 */
export interface UgcLevelConfig {
  level: number;
  min_pct: number;
  max_pct: number | null;
  label: string;
  consequence: string;
  action_window_months: number | null;
}

export interface UgcLevelResult {
  match: UgcLevelConfig;
  /** Set when the input wasn't already net of references/quotes/etc. */
  exclusionNote: string | null;
}

/**
 * Finds the matching level for a similarity percentage. Levels are
 * contiguous ranges (each level's min_pct equals the previous level's
 * max_pct) with the upper bound inclusive, e.g. "Level 0 <=10%, Level 1
 * >10-40%" - so only the lowest configured level treats its min_pct as
 * inclusive too.
 */
export function findUgcLevel(
  similarityPercent: number,
  levels: UgcLevelConfig[],
): UgcLevelConfig | null {
  const sorted = [...levels].sort((a, b) => a.min_pct - b.min_pct);
  return (
    sorted.find((level, index) => {
      const passesLower =
        index === 0 ? similarityPercent >= level.min_pct : similarityPercent > level.min_pct;
      const passesUpper = level.max_pct == null || similarityPercent <= level.max_pct;
      return passesLower && passesUpper;
    }) ?? null
  );
}

export function calculateUgcLevel(
  similarityPercent: number,
  excludedReferencesAlready: boolean,
  levels: UgcLevelConfig[],
): UgcLevelResult | null {
  const match = findUgcLevel(similarityPercent, levels);
  if (!match) return null;

  return {
    match,
    exclusionNote: excludedReferencesAlready
      ? null
      : "This figure may include references, quotes and other exclusions. The official report generated by your institution excludes these automatically - your real level may be lower.",
  };
}
